#!/bin/sh
set -eu
# trigger a CI release by tagging with next patch version

tag=$(git describe --tags --abbrev=0)

patch=$(echo "$tag" | grep -o '[0-9]*$')
prefix=${tag%$patch}

next_patch=$(( $patch + 1))
next_tag="$prefix$next_patch"

echo "$tag -> $next_tag - press enter to tag and push"

read

git tag $next_tag
git push origin $next_tag
