language: ruby
rvm:
  - 2.0.0

os:
  # - linux
  - osx

install: |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-get update >/dev/null
    sudo apt-get install -y zsh
  else
    brew update >/dev/null
    brew install zsh
  fi

script:
  - "./bin/dotfiles symlinks"
  - "./bin/dotfiles install"
  - "./bin/dotfiles gitconfig"
  - "./bin/dotfiles antibody"
  - "./bin/dotfiles update"
