#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# symlink configs
mkdir -p ~/.config
# ZSH
ln -nfs $DOTFILES/zsh $HOME/.config/zsh
ln -nfs $DOTFILES/zsh/.zshenv $HOME/.zshenv

# alacritty terminal
ln -nfs $DOTFILES/alacritty $HOME/.config/alacritty

# neovim
ln -nfs $DOTFILES/nvim $HOME/.config/nvim

# kitty terminal
ln -nfs $DOTFILES/kitty $HOME/.config/kitty

# skhd
ln -nfs $DOTFILES/skhd $HOME/.config/skhd

# spacebar
ln -nfs $DOTFILES/spacebar $HOME/.config/spacebar

# sketchybar
ln -nfs $DOTFILES/sketchybar $HOME/.config/sketchybar

# yabai
ln -nfs $DOTFILES/yabai $HOME/.config/yabai

# git
ln -nfs $DOTFILES/git/gitignore_global $HOME/.gitignore_global

# asdf
ln -nfs $DOTFILES/asdf/asdfrc $HOME/.asdfrc

# ssh
mkdir -p ~/.ssh
ln -nfs $DOTFILES/.ssh/config $HOME/.ssh/config
