# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true
command_timeout = 1000

# ~/.config/starship.toml

# A continuation prompt that displays two filled-in arrows
continuation_prompt = '..❯ '

[character]
success_symbol = '[❯](green)'

