#!/usr/bin/env bash

# Install command-line tools using Homebrew
# Usage: `brew bundle Brewfile`

# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
install coreutils
# Install some other useful utilities like `sponge`
install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
install findutils

# Install more recent versions of some OS X tools
install vim --override-system-vi
install homebrew/dupes/grep
# Install other useful binaries

install ack
install git
install git-extras
install heroku-toolbelt
install hub
install hubflow
install imagemagick --with-webp
install ssh-copy-id


# Remove outdated versions from the cellar
cleanup
