#!/usr/bin/env bash

# Install native apps
# Usage: `brew bundle Caskfile`

install phinze/cask/brew-cask
tap caskroom/versions

cask install alfred 2> /dev/null
cask install caffeine 2> /dev/null
cask install charles 2> /dev/null
cask install cheat-sheet 2> /dev/null
cask install chromium 2> /dev/null
cask install dash 2> /dev/null
cask install dropbox 2> /dev/null
cask install firefox 2> /dev/null
cask install google-chrome 2> /dev/null
cask install google-chrome-canary 2> /dev/null
cask install heroku-toolbelt 2> /dev/null
cask install iterm2-beta 2> /dev/null
cask install kaleidoscope 2> /dev/null
cask install opera 2> /dev/null
cask install opera-developer 2> /dev/null
cask install opera-next 2> /dev/null
cask install sidestep 2> /dev/null
cask install slate 2> /dev/null
cask install sublime-text 2> /dev/null
cask install transmission 2> /dev/null
cask install transmit 2> /dev/null
cask install vagrant 2> /dev/null
cask install vlc 2> /dev/null
