return {
  { import = 'plugins.lsp.core' },
  { import = 'plugins.lang.astro' },
  { import = 'plugins.lang.cmake' },
  { import = 'plugins.lang.docker' },
  { import = 'plugins.lang.elixir' },
  { import = 'plugins.lang.go' },
  { import = 'plugins.lang.json' },
  { import = 'plugins.lang.php' },
  { import = 'plugins.lang.python' },
  { import = 'plugins.lang.rust' },
  { import = 'plugins.lang.tailwind' },
  { import = 'plugins.lang.terraform' },
  { import = 'plugins.lang.typescript' },
  { import = 'plugins.lang.yaml' },
  { import = 'plugins.formatting.prettier' },
  { import = 'plugins.linting.eslint' },
  { import = 'plugins.dap.core' },
  { import = 'plugins.test.core' },
}
