#!/bin/bash

apm install angularjs
apm install atom-angularjs
apm install atom-beautify
apm install atom-color-highlight
apm install autocomplete-paths
apm install autocomplete-plus
apm install autocomplete-snippets
apm install cowsay
apm install dash
apm install easy-motion
apm install fancy-new-file
apm install fixmyjs
apm install gist-it
apm install git-blame
apm install git-history
apm install git-log
apm install javascript-snippets
apm install js-refactor
apm install jumpy
apm install key-peek
apm install language-fish-shell
apm install language-git
apm install language-todo
apm install linter
apm install linter-jshint
apm install linter-less
apm install linter-phpmd
apm install linter-phpcs
apm install linter-php
apm install markdown-table-formatter
apm install pain-split
apm install refactor
apm install regex-railroad-diagram
apm install seti-syntax
apm install seti-ui
apm install tasks
apm install test-status
apm install todo-show
apm install unity-ui
apm install vim-mode
