name: Tests
on:
  push:
    branches: [master]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Symlinks
        run: ./bin/dotfiles symlinks
      - name: Install - antibody
        run: ./bin/dotfiles install antibod
      - name: Install - asdf
        run: ./bin/dotfiles install asdf
