name: Tests
on:
  push:
    branches: [master]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Symlinks
        run: ./bin/dotfiles symlinks
      - name: Install - antibody
        run: ./bin/dotfiles install antibody
      - name: Install - asdf
        run: ./bin/dotfiles install asdf
      - name: Install - docker
        run: ./bin/dotfiles install docker
      - name: Install - elixir
        run: ./bin/dotfiles install elixir
      - name: Install - fzf
        run: ./bin/dotfiles install fzf
      - name: Install - git
        run: ./bin/dotfiles install git
      - name: Install - homebrew
        run: ./bin/dotfiles install homebrew
      - name: Install - macos
        run: ./bin/dotfiles install macos
      - name: Install - nodejs
        run: ./bin/dotfiles install nodejs
      - name: Install - ssh
        run: ./bin/dotfiles install ssh
      - name: Install - vim
        run: ./bin/dotfiles install vim
      - name: Install - xcode
        run: ./bin/dotfiles install xcode
